macOS compatibility

diff --git a/usr/local/bin/WLANderlust b/usr/local/bin/WLANderlust
--- a/usr/local/bin/WLANderlust
+++ b/usr/local/bin/WLANderlust
@@ -12,8 +12,8 @@
 usage()
 {
 	if $ROOT; then
-		echo -e '\e[1mWLANderlust
-\e[2mNot all those who WLANder have lost connection\e[0m
+		echo -e '\x1B[1mWLANderlust
+\x1B[2mNot all those who WLANder have lost connection\x1B[0m
 
 Usage:
   -h, --help
@@ -33,8 +33,8 @@ Usage:
   --verbose
   --debug'
   	else
-	  	echo -e '\e[1mWLANderlust
-\e[2mNot all those who WLANder have lost connection\e[0m
+	  	echo -e '\x1B[1mWLANderlust
+\x1B[2mNot all those who WLANder have lost connection\x1B[0m
 
 Usage:
   -h, --help
@@ -62,10 +62,25 @@ logError()
 {
 	[[ -t 1 || -p /dev/stdin ]] &&
 		# Set text color to bold red
-		echo -e "\e[1m\e[31m$@\e[0m" > /dev/stderr
+		echo -e "\x1B[1m\x1B[31m$@\x1B[0m" > /dev/stderr
 	[ ! -z "$LOGFILE" ] && [ "$LOGFILE" != '/dev/stdout' ] &&
 		echo "`date` $INTERFACE $SCRIPTNAME $@" >> "$LOGFILE"
 }
+
+# macOS compatibility
+if ! which realpath; then
+	realpath() {
+		[[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
+	}
+fi
+if ! which md5sum; then
+	md5sum() {
+		[ -z "$1" ] &&
+			md5 ||
+			md5 "$1"
+	}
+fi
+
 
 MYDIR="${BASH_SOURCE%/*}"
 [[ ! -d "$MYDIR" ]] && MYDIR="$PWD"
@@ -116,9 +131,9 @@ getConfigValue()
 	readConfig
 
 	# Lookup key value in the configuration
-	VALUE=`sed -n "s|^$1=['\"]\?\([^'\"]*\)['\"]\?$|\1|p" <<< "$CONFIG"`
+	VALUE=`sed -n "s|^$1=['\"]\{0,1\}\([^'\"]*\)['\"]\{0,1\}$|\1|p" <<< "$CONFIG"`
 	# If value is empty lookup the key value in the default configuration
-	[ -z "$VALUE" ] && VALUE=`sed -n "s|^$1=['\"]\?\([^'\"]*\)['\"]\?$|\1|p" <<< "$DEFAULTCONFIG"`
+	[ -z "$VALUE" ] && VALUE=`sed -n "s|^$1=['\"]\{0,1\}\([^'\"]*\)['\"]\{0,1\}$|\1|p" <<< "$DEFAULTCONFIG"`
 	# If value is empty use the default value
 	[ -z "$VALUE" ] && VALUE="$2"
 
@@ -151,8 +166,8 @@ storeConfig()
 		return
 
 	# Check if new the configuration changes from the old configuration by comparing the MD5 sums
-	OLDMD5=`md5sum -t "$CONFIGFILE" | awk '{ print $1 }'`
-	NEWMD5=`md5sum -t - <<< "$CONFIG"`
+	OLDMD5=`md5sum "$CONFIGFILE" | awk '{ print $1 }'`
+	NEWMD5=`md5sum <<< "$CONFIG"`
 	if [ "$OLDMD5" != "$NEWMD5" ]; then
 		if touch "$CONFIGFILE"; then
 			# The MD5 sum differences, we're dealing with a new configuration, update the configuration
@@ -295,9 +310,12 @@ if [ -f '/etc/hostapd/hostapd.conf' ]; then
 	HOSTAPTXPOWER=`sed -n 's|.*txpower \([0-9.]*\) dBm$|\1|p' <<< "$_IWDEVINFO"`
 fi
 
-DEFAULTROUTEINTERFACE=`route -n | sed -n 's|^0\.0\.0\.0 .* \([^ ]*\)$|\1|p'`
+[ "`uname`" = 'Linux' ] &&
+	DEFAULTROUTEINTERFACE=`route -n | sed -n 's|^0\.0\.0\.0 .* \([^ ]*\)$|\1|p' | uniq | sed "/lo/d;/tun[0-9]*/d;/dns[0-9]*/d"`
+[ "`uname`" = 'Darwin' ] &&
+	DEFAULTROUTEINTERFACE=`netstat -nr | grep '^default' | awk '{ print $6 }'`
 # If no interface is given try to figure out which interface to use
-if [ -z "$INTERFACE" ] && [ ! -z `sed "/lo/d;/tun[0-9]*/d;/dns[0-9]*/d;/$HOSTAPINTERFACE/d" <<< "$DEFAULTROUTEINTERFACE"` ]; then
+if [ -z "$INTERFACE" ] && [ ! -z "$DEFAULTROUTEINTERFACE" ] && [ "$DEFAULTROUTEINTERFACE" != "$HOSTAPINTERFACE" ]; then
 	INTERFACE="$DEFAULTROUTEINTERFACE"
 	logMessage "No network interface defined, using default route interface $DEFAULTROUTEINTERFACE"
 elif [ -z "$INTERFACE" ]; then
@@ -408,8 +426,8 @@ storeState()
 			logError "Can't write to status file"
 	else
 		# Check if new the state changes from the old state by comparing the MD5 sums
-		OLDMD5=`md5sum -t "$STATEFILE" | awk '{ print $1 }'`
-		NEWMD5=`md5sum -t - <<< "$STATE" | awk '{ print $1 }'`
+		OLDMD5=`md5sum "$STATEFILE" | awk '{ print $1 }'`
+		NEWMD5=`md5sum <<< "$STATE" | awk '{ print $1 }'`
 		if [ "$OLDMD5" != "$NEWMD5" ]; then
 			# The MD5 sum differences, we're dealing with a new state, update the state
 			$DEBUGLOGGING && logMessage 'State changed' &&
@@ -659,7 +677,12 @@ getWiFiStatus()
 			grep -q '^\swpa-roam ' "/etc/network/interfaces.d/$INTERFACE" && ISROAMING='true'
 		fi
 	elif $INTERFACEISUP && $ISWIFIINTERFACE && [ "`uname`" = 'Darwin' ]; then
-		setState 'SSID' `networksetup -getairportnetwork "$INTERFACE" | sed -n 's|^Current Wi-Fi Network: ||p'`
+		_AIRPORT=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport en0 -I`
+		setState 'BSSID' `sed -n 's|^[[:space:]]*BSSID: ||p' <<< "$_AIRPORT"`
+		setState 'SSID' `sed -n 's|^[[:space:]]*SSID: ||p' <<< "$_AIRPORT"`
+		setState 'WPASTATE' ''
+		[ ! -z "$SSID" ] &&
+			setState 'WPASTATE' 'COMPLETED'
 	else
 		setState 'BSSID' ''
 		setState 'SSID' ''
@@ -714,13 +737,16 @@ startDHClient()
 [ -z "$WHATISMYIPURL" ] && WHATISMYIPURL=`getConfigValue 'WHATISMYIPURL'`
 getNetworkStatus()
 {
-	setState 'DEFAULTROUTEINTERFACE' `route -n | sed -n 's|^0\.0\.0\.0 .* \([^ ]*\)$|\1|p'`
+	[ "`uname`" = 'Linux' ] &&
+		setState 'DEFAULTROUTEINTERFACE' `route -n | sed -n 's|^0\.0\.0\.0 .* \([^ ]*\)$|\1|p'`
+	[ "`uname`" = 'Darwin' ] &&
+		setState 'DEFAULTROUTEINTERFACE' `netstat -nr | grep '^default' | awk '{ print $6 }'`
 
 	IFCONFIG=`ifconfig "$INTERFACE"`
 	grep -q '<UP' <<< "$IFCONFIG" &&
 		INTERFACEISUP='true' ||
 		INTERFACEISUP='false'
-	MACADDRESS=`sed -n 's|^.* ether \([a-z0-9:]*\) .*$|\1|p' <<< "$IFCONFIG"`
+	MACADDRESS=`sed -n 's|^[[:space:]]*ether \([a-z0-9:]*\) .*$|\1|p' <<< "$IFCONFIG"`
 
 	if ! $INTERFACEISUP; then
 		# Interface is down
@@ -878,9 +904,9 @@ editwpa_supplicant()
 	fi
 	. ~/.selected_editor
 
-	OLDMD5=`md5sum -t "$WPASUPPLICANTCONF" | awk '{ print $1 }'`
+	OLDMD5=`md5sum "$WPASUPPLICANTCONF" | awk '{ print $1 }'`
 	"$SELECTED_EDITOR" "$WPASUPPLICANTCONF"
-	NEWMD5=`md5sum -t "$WPASUPPLICANTCONF" | awk '{ print $1 }'`
+	NEWMD5=`md5sum "$WPASUPPLICANTCONF" | awk '{ print $1 }'`
 
 	[ "$OLDMD5" = "$NEWMD5" ] &&
 		return 0
@@ -1037,6 +1063,9 @@ toggleRoaming()
 # IP over DNS tunneling functions
 isIPoverDNSactive()
 {
+	[ "`uname`" != 'Linux' ] &&
+		return
+
 	SCRIPTNAME="$LIBPATH/ipoverdns"
 	. "$SCRIPTNAME" STATE
 	SCRIPTNAME="$0"
@@ -1049,6 +1078,9 @@ isIPoverDNSactive
 
 startIPoverDNStunneling()
 {
+	[ "`uname`" != 'Linux' ] &&
+		return
+
 	SCRIPTNAME="$LIBPATH/ipoverdns"
 	. "$SCRIPTNAME" START
 	SCRIPTNAME="$0"
@@ -1060,6 +1092,9 @@ startIPoverDNStunneling()
 
 stopIPoverDNStunneling()
 {
+	[ "`uname`" != 'Linux' ] &&
+		return
+
 	SCRIPTNAME="$LIBPATH/ipoverdns"
 	. "$SCRIPTNAME" STOP
 	SCRIPTNAME="$0"
@@ -1068,6 +1103,9 @@ stopIPoverDNStunneling()
 # VPN functions
 isVPNactive()
 {
+	[ "`uname`" != 'Linux' ] &&
+		return
+
 	SCRIPTNAME="$LIBPATH/vpn"
 	. "$SCRIPTNAME" STATE
 	SCRIPTNAME="$0"
@@ -1080,6 +1118,9 @@ isVPNactive
 
 startVPN()
 {
+	[ "`uname`" != 'Linux' ] &&
+		return
+
 	SCRIPTNAME="$LIBPATH/vpn"
 	. "$SCRIPTNAME" START
 	SCRIPTNAME="$0"
@@ -1091,6 +1132,9 @@ startVPN()
 
 stopVPN()
 {
+	[ "`uname`" != 'Linux' ] &&
+		return
+
 	SCRIPTNAME="$LIBPATH/vpn"
 	. "$SCRIPTNAME" STOP
 	SCRIPTNAME="$0"
@@ -1153,23 +1197,23 @@ WLANderlustConfigurationMenu()
 {
 	while true; do
 		! $VERBOSELOGGING && clear
-		echo -e '\e[1mWLANderlust'
-		echo -e '\e[2mNot all those who WLANder have lost connection\e[0m'
+		echo -e '\x1B[1mWLANderlust'
+		echo -e '\x1B[2mNot all those who WLANder have lost connection\x1B[0m'
 		echo 'Configuration Menu'
 		echo
-		echo -e "  \e[1mW\e[0m Edit "`sed 's|^\([^Ww]*\)\([Ww]\)\(.*\)$|\1\\\\e[1m\2\\\\e[0m\3|' <<< "$WPASUPPLICANTCONF"`
-		echo -e '  \e[1mC\e[0m Configure \e[1mC\e[0maptive Portal'
-		echo -e '  \e[1mD\e[0m Configure IP over \e[1mD\e[0mNS tunneling'
-		echo -e '  \e[1mV\e[0m Configure \e[1mV\e[0mPN'
+		echo -e "  \x1B[1mW\x1B[0m Edit "`sed 's|^\([^Ww]*\)\([Ww]\)\(.*\)$|\1\\\\x1B[1m\2\\\\x1B[0m\3|' <<< "$WPASUPPLICANTCONF"`
+		echo -e '  \x1B[1mC\x1B[0m Configure \x1B[1mC\x1B[0maptive Portal'
+		echo -e '  \x1B[1mD\x1B[0m Configure IP over \x1B[1mD\x1B[0mNS tunneling'
+		echo -e '  \x1B[1mV\x1B[0m Configure \x1B[1mV\x1B[0mPN'
 		$ISWIFIINTERFACE && $ISROAMING &&
-			echo -e '  \e[1mR\e[0m Disable \e[1mr\e[0moaming'
+			echo -e '  \x1B[1mR\x1B[0m Disable \x1B[1mr\x1B[0moaming'
 		$ISWIFIINTERFACE && ! $ISROAMING &&
-			echo -e '  \e[1mR\e[0m Enable \e[1mR\e[0moaming'
+			echo -e '  \x1B[1mR\x1B[0m Enable \x1B[1mR\x1B[0moaming'
 		$SHOWPASSWORDS &&
-			echo -e '  \e[1mP\e[0m Hide \e[1mP\e[0masswords' ||
-			echo -e '  \e[1mP\e[0m Show \e[1mP\e[0masswords'
-		echo -e '  \e[1mB\e[0m \e[1mB\e[0mack to main menu'
-		echo -e '  \e[1mQ\e[0m \e[1mQ\e[0muit'
+			echo -e '  \x1B[1mP\x1B[0m Hide \x1B[1mP\x1B[0masswords' ||
+			echo -e '  \x1B[1mP\x1B[0m Show \x1B[1mP\x1B[0masswords'
+		echo -e '  \x1B[1mB\x1B[0m \x1B[1mB\x1B[0mack to main menu'
+		echo -e '  \x1B[1mQ\x1B[0m \x1B[1mQ\x1B[0muit'
 		echo
 
 		# Flush stdin
@@ -1201,8 +1245,8 @@ WLANderlustMenu()
 		getWiFiStatus
 		getNetworkStatus
 		! $VERBOSELOGGING && clear
-		echo -e '\e[1mWLANderlust'
-		echo -e '\e[2mNot all those who WLANder have lost connection\e[0m'
+		echo -e '\x1B[1mWLANderlust'
+		echo -e '\x1B[2mNot all those who WLANder have lost connection\x1B[0m'
 		showWiFiStatus
 		isCaptivePortalPresent
 		showNetworkStatus
@@ -1232,7 +1276,7 @@ WLANderlustMenu()
 					echo -n ' '
 				fi
 
-				printf '\e[1m%2d\e[0m' $I
+				printf '\x1B[1m%2d\x1B[0m' $I
 
 				# Print a floppy character if the SSID is already configured in the WPA supplicant configuration
 				grep -q "^\sssid=\"$_SSID\"" "$WPASUPPLICANTCONF" &&
@@ -1254,32 +1298,32 @@ WLANderlustMenu()
 			done
 		fi
 		$SCANFORNETWORKS &&
-			echo -e '  \e[1mM\e[0m \e[1mM\e[0manual'
+			echo -e '  \x1B[1mM\x1B[0m \x1B[1mM\x1B[0manual'
 
 		$SCANFORNETWORKS &&
-			echo -e '  \e[1mW\e[0m Stop scanning W\e[0miFi for networks' ||
-			echo -e '  \e[1mW\e[0m Scan for \e[1mW\e[0miFi networks'
+			echo -e '  \x1B[1mW\x1B[0m Stop scanning W\x1B[0miFi for networks' ||
+			echo -e '  \x1B[1mW\x1B[0m Scan for \x1B[1mW\x1B[0miFi networks'
 		$SCANFORNETWORKS &&
 			[ "$WPASTATE" = 'COMPLETED' ] &&
-			echo -e "  \e[1mA\e[0m Re\e[1ma\e[0mssociate interface $INTERFACE"
+			echo -e "  \x1B[1mA\x1B[0m Re\x1B[1ma\x1B[0mssociate interface $INTERFACE"
 		(! $ISWIFIINTERFACE || [ "$WPASTATE" = 'COMPLETED' ]) &&
 			[ "$CAPTIVEPORTALSTATE" != 'none' ] &&
 			[ "$CAPTIVEPORTALSTATE" != 'solved' ] &&
-			echo -e '  \e[1mS\e[0m \e[1mS\e[0molve Captive Portal'
+			echo -e '  \x1B[1mS\x1B[0m \x1B[1mS\x1B[0molve Captive Portal'
 		(! $ISWIFIINTERFACE || [ "$WPASTATE" = 'COMPLETED' ]) &&
 			(([ "$CAPTIVEPORTALSTATE" != 'none' ] && [ "$CAPTIVEPORTALSTATE" != 'solved' ]) || $FORCE) &&
 			[ "$IPOVERDNSSTATE" = 'stopped' ] &&
 			[ "$VPNSTATE" = 'stopped' ] &&
-			echo -e '  \e[1mD\e[0m Start IP over \e[1mD\e[0mNS tunneling'
+			echo -e '  \x1B[1mD\x1B[0m Start IP over \x1B[1mD\x1B[0mNS tunneling'
 		[ "$IPOVERDNSSTATE" != 'stopped' ] && [ "$VPNSTATE" = 'stopped' ] &&
-			echo -e '  \e[1mD\e[0m Stop IP over \e[1mD\e[0mNS tunneling'
+			echo -e '  \x1B[1mD\x1B[0m Stop IP over \x1B[1mD\x1B[0mNS tunneling'
 		(! $ISWIFIINTERFACE || [ "$WPASTATE" = 'COMPLETED' ]) &&
 			([ "$CAPTIVEPORTALSTATE" = 'none' ] || [ "$CAPTIVEPORTALSTATE" = 'solved' ]) &&
 			[ "$VPNSTATE" = 'stopped' ] &&
-			echo -e '  \e[1mV\e[0m Start \e[1mV\e[0mPN'
-		[ "$VPNSTATE" != 'stopped' ] && echo -e '  \e[1mV\e[0m Stop \e[1mV\e[0mPN'
-		echo -e '  \e[1mC\e[0m \e[1mC\e[0monfigure WLANderlust'
-		echo -e '  \e[1mQ\e[0m \e[1mQ\e[0muit'
+			echo -e '  \x1B[1mV\x1B[0m Start \x1B[1mV\x1B[0mPN'
+		[ "$VPNSTATE" != 'stopped' ] && echo -e '  \x1B[1mV\x1B[0m Stop \x1B[1mV\x1B[0mPN'
+		echo -e '  \x1B[1mC\x1B[0m \x1B[1mC\x1B[0monfigure WLANderlust'
+		echo -e '  \x1B[1mQ\x1B[0m \x1B[1mQ\x1B[0muit'
 		echo
 
 		# Flush stdin
@@ -1339,7 +1383,7 @@ WLANderlustMenu()
 						configureWiFi "$_SSID" "$SSIDINFO"
 						break
 					else
-						echo -en '\t\e[1m\e[31mInvalid input\e[0m\r'
+						echo -en '\t\x1B[1m\x1B[31mInvalid input\x1B[0m\r'
 					fi
 					;;
 			esac
@@ -1355,8 +1399,8 @@ if $INTERACTIVE && ! $STATUS; then
 	else
 		getWiFiStatus
 		getNetworkStatus
-		echo -e '\e[1mWLANderlust'
-		echo -e '\e[2mNot all those who WLANder have lost connection\e[0m'
+		echo -e '\x1B[1mWLANderlust'
+		echo -e '\x1B[2mNot all those who WLANder have lost connection\x1B[0m'
 		showWiFiStatus
 		isCaptivePortalPresent
 		showNetworkStatus
@@ -1370,7 +1414,8 @@ if $INTERACTIVE && ! $STATUS; then
 			storeState
 		fi
 
-		echo 'Run as root for more options'
+		[ "`uname`" = 'Linux' ] &&
+			echo 'Run as root for more options'
 	fi
 else
 		if $ROOT; then
