Improved start/stop procedure

diff --git a/usr/local/lib/WLANderlust/vpn.d/sshtunnel b/usr/local/lib/WLANderlust/vpn.d/sshtunnel
--- a/usr/local/lib/WLANderlust/vpn.d/sshtunnel
+++ b/usr/local/lib/WLANderlust/vpn.d/sshtunnel
@@ -21,6 +21,8 @@ HASCONFIG='true'
 	ISCONFIGURED='true' ||
 	ISCONFIGURED='false'
 
+SSHTUNNELCTRLSOCKET="/var/run/sshtunnel.$INTERFACE.socket"
+
 case "$1" in
 	'CONFIGURE')
 		# Ask for VPN server hostname
@@ -72,9 +74,8 @@ case "$1" in
 			return 1
 		else
 			#ToDo Pick a 'random' IP address if multiple addresses have been returned
-			VPNSERVERIPADDRESS=`sed 's/^.* has address //g' <<< "$VPNSERVERIPADDRESS" | head -n 1`
+			setState 'VPNSERVERIPADDRESS' `sed 's/^.* has address //g' <<< "$VPNSERVERIPADDRESS" | head -n 1`
 
-			# Ping doesn't seem to work with my provider
 			if ! nc -s "$VPNBINDIPADDRESS" -4 -w "$TIMEOUT" -z "$VPNSERVERIPADDRESS" 22 > /dev/null 2>&1; then
 				logError "Unable to connect to SSH port on VPN server IP address $VPNSERVERIPADDRESS"
 				return 1
@@ -111,25 +112,29 @@ case "$1" in
 
 
 			if [ "$IPOVERDNSSTATE" = 'started' ] && ssh -f \
+				-M -S "$SSHTUNNELCTRLSOCKET" \
 				-o 'PermitLocalCommand=yes' \
 				-o "LocalCommand=ifconfig '$VPNINTERFACE' 192.168.244.2 pointopoint 192.168.244.1 netmask 255.255.255.0" \
 				-o 'ServerAliveInterval=5' \
 				-o "ConnectTimeout=$TIMEOUT" \
+				-o "ExitOnForwardFailure=yes" \
 				-b "$IPOVERDNSIPADDRESS" \
 				-w 0:0 "$SSHTUNNELUSERNAME@$VPNSERVERIPADDRESS" \
 				'sudo ifconfig tun0 192.168.244.1 pointopoint 192.168.244.2 netmask 255.255.255.0'; then
+				while [ ! -e "$SSHTUNNELCTRLSOCKET" ]; do sleep 0.1; done
 				logMessage 'Created SSH Tunnel'
-				sleep 2
 			elif ssh -f \
+				-M -S "$SSHTUNNELCTRLSOCKET" \
 				-o 'PermitLocalCommand=yes' \
 				-o "LocalCommand=ifconfig '$VPNINTERFACE' 192.168.244.2 pointopoint 192.168.244.1 netmask 255.255.255.0" \
 				-o 'ServerAliveInterval=5' \
 				-o "ConnectTimeout=$TIMEOUT" \
 				-b "$VPNBINDIPADDRESS" \
+				-o "ExitOnForwardFailure=yes" \
 				-w 0:0 "$SSHTUNNELUSERNAME@$VPNSERVERIPADDRESS" \
 				'sudo ifconfig tun0 192.168.244.1 pointopoint 192.168.244.2 netmask 255.255.255.0'; then
+				while [ ! -e "$SSHTUNNELCTRLSOCKET" ]; do sleep 0.1; done
 				logMessage 'Created SSH Tunnel'
-				sleep 2
 			else
 				logError 'Failed to create SSH Tunnel'
 				return 1
@@ -143,24 +148,16 @@ case "$1" in
 		fi
 		;;
 	'STOP')
-		# Get PID of SSH tunnel
+		if [ -e "$SSHTUNNELCTRLSOCKET" ]; then
+			VPNINTERFACE=`getState 'VPNINTERFACE'`
+			VPNSERVERIPADDRESS=`getState 'VPNSERVERIPADDRESS'`
 
-		#ToDo Replace with pgrep
-		PROCESSINFO=`ps -ef | grep ".* ssh .* -o LocalCommand=ifconfig 'tun[0-9]' .* -b $VPNBINDIPADDRESS .* $SSHTUNNELUSERNAME@[0-9.]* .*"`
-		$DEBUGLOGGING && logMessage "PROCESSINFO=$PROCESSINFO"
-		if [ ! -z "$PROCESSINFO" ]; then
-			PID=`awk '{ print $2 }' <<< "$PROCESSINFO"`
 			logMessage 'Stopping SSH tunnel'
-			$VERBOSELOGGING && logMessage "SSH tunnel PID: $PID"
-			setState 'VPNINTERFACE' `sed -n "s|.* LocalCommand=ifconfig '\(tun[0-9]*\)' .*|\1|p" <<< "$PROCESSINFO"` #'
-			$VERBOSELOGGING && logMessage "SSH tunnel TUN interface: $VPNINTERFACE"
-			setState 'VPNSERVERIPADDRESS' `sed -n "s|.* $SSHTUNNELUSERNAME@\([0-9.]*\) .*|\1|p" <<< "$PROCESSINFO"`
-			$VERBOSELOGGING && logMessage "VPN server IP address: $VPNSERVERIPADDRESS"
 
-			if kill "$PID"; then
+			if ssh -S "$SSHTUNNELCTRLSOCKET" -O exit "$SSHTUNNELUSERNAME@$VPNSERVERIPADDRESS"; then
 				logMessage 'SSH tunnel stopped'
 			else
-				logError "Failed to stop SSH tunnel PID: $PID"
+				logError "Failed to stop SSH tunnel"
 				return 1
 			fi
 
@@ -175,25 +172,16 @@ case "$1" in
 					return 1
 				fi
 			else
-				logError "TUN interface $VPNINTERFACE does not exist"
+				logError "TUN interface $VPNINTERFACE does not exist, this should not happen"
 			fi
 		fi
 
 		return 0
 		;;
 	'STATE')
-		#ToDo Replace with pgrep
-		PROCESSINFO=`ps -ef | grep ".* ssh .* -o LocalCommand=ifconfig 'tun[0-9]' .* -b $VPNBINDIPADDRESS .* $SSHTUNNELUSERNAME@[0-9.]* .*"`
-		$DEBUGLOGGING && logMessage "PROCESSINFO=$PROCESSINFO"
-		PID=`awk '{ print $2 }' <<< "$PROCESSINFO"`
-		if [ ! -z "$PID" ]; then
-			$VERBOSELOGGING && logMessage "SSH tunnel PID: $PID"
-			setState 'VPNINTERFACE' `sed -n "s|.* LocalCommand=ifconfig '\(tun[0-9]*\)' .*|\1|p" <<< "$PROCESSINFO"` #'
-			$VERBOSELOGGING && logMessage "SSH tunnel TUN interface: $VPNINTERFACE"
-			VPNSERVERIPADDRESS=`sed -n "s|.* $SSHTUNNELUSERNAME@\([0-9.]*\) .*|\1|p" <<< "$PROCESSINFO"`
-			$VERBOSELOGGING && logMessage "VPN server IP address: $VPNSERVERIPADDRESS"
-			$DEBUGLOGGING && logMessage "$VPNINTERFACE = $DEFAULTROUTEINTERFACE"
-			VPNSERVERHOSTNAME="$SSHTUNNELSERVERHOSTNAME"
+		if [ -e "$SSHTUNNELCTRLSOCKET" ]; then
+			VPNINTERFACE=`getState 'VPNINTERFACE'`
+			VPNSERVERIPADDRESS=`getState 'VPNSERVERIPADDRESS'`
 			return 0
 		fi
 
